CGHCPPRELOAD_SRC_LIB := cghcppreload.c
CGHCPPRELOAD_SRC := $(CGHCPPRELOAD_SRC_LIB) cghcppreloadtest.c

CGHCPPRELOAD_SRC_LIB := $(patsubst %,$(DIRCGHCPPRELOAD)/%,$(CGHCPPRELOAD_SRC_LIB))
CGHCPPRELOAD_SRC := $(patsubst %,$(DIRCGHCPPRELOAD)/%,$(CGHCPPRELOAD_SRC))

CGHCPPRELOAD_OBJ_LIB := $(patsubst %.c,%.o,$(CGHCPPRELOAD_SRC_LIB))
CGHCPPRELOAD_OBJ := $(patsubst %.c,%.o,$(CGHCPPRELOAD_SRC))

CGHCPPRELOAD_DEP_LIB := $(patsubst %.c,%.d,$(CGHCPPRELOAD_SRC_LIB))
CGHCPPRELOAD_DEP := $(patsubst %.c,%.d,$(CGHCPPRELOAD_SRC))

CFLAGS_CGHCPPRELOAD := -I$(DIRCLILIB) -I$(DIRMISC)
LIBS_CGHCPPRELOAD := $(DIRCLILIB)/libclilib.a

MAKEFILES_CGHCPPRELOAD := $(DIRCGHCPPRELOAD)/module.mk

.PHONY: CGHCPPRELOAD clean_CGHCPPRELOAD distclean_CGHCPPRELOAD unit_CGHCPPRELOAD $(LCCGHCPPRELOAD) clean_$(LCCGHCPPRELOAD) distclean_$(LCCGHCPPRELOAD) unit_$(LCCGHCPPRELOAD)

$(LCCGHCPPRELOAD): CGHCPPRELOAD
clean_$(LCCGHCPPRELOAD): clean_CGHCPPRELOAD
distclean_$(LCCGHCPPRELOAD): distclean_CGHCPPRELOAD
unit_$(LCCGHCPPRELOAD): unit_CGHCPPRELOAD

CGHCPPRELOAD: $(DIRCGHCPPRELOAD)/libcghcppreload.a $(DIRCGHCPPRELOAD)/libcghcppreload.so $(DIRCGHCPPRELOAD)/cghcppreloadtest

unit_CGHCPPRELOAD:
	@true

$(DIRCGHCPPRELOAD)/libcghcppreload.a: $(CGHCPPRELOAD_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPRELOAD)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRCGHCPPRELOAD)/libcghcppreload.so: $(DIRCGHCPPRELOAD)/libcghcppreload.a $(LIBS_CGHCPPRELOAD) $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPRELOAD)
	$(CC) -shared -fPIC -o $(DIRCGHCPPRELOAD)/libcghcppreload.so -Wl,--whole-archive $(filter %.a,$^) -Wl,--no-whole-archive -ldl -lc

$(DIRCGHCPPRELOAD)/cghcppreloadtest: $(DIRCGHCPPRELOAD)/cghcppreloadtest.o $(LIBS_CGHCPPRELOAD) $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPRELOAD)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_CGHCPPRELOAD)

$(CGHCPPRELOAD_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPRELOAD)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_CGHCPPRELOAD)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_CGHCPPRELOAD)

$(CGHCPPRELOAD_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPRELOAD)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_CGHCPPRELOAD)

clean_CGHCPPRELOAD:
	rm -f $(CGHCPPRELOAD_OBJ) $(CGHCPPRELOAD_DEP)

distclean_CGHCPPRELOAD: clean_CGHCPPRELOAD
	rm -f $(DIRCGHCPPRELOAD)/libcghcppreload.a $(DIRCGHCPPRELOAD)/cghcppreloadtest

-include $(DIRCGHCPPRELOAD)/*.d
