CGHCPPROXYCMD_SRC_LIB :=
CGHCPPROXYCMD_SRC := $(CGHCPPROXYCMD_SRC_LIB) cghcpproxycmd.c

CGHCPPROXYCMD_SRC_LIB := $(patsubst %,$(DIRCGHCPPROXYCMD)/%,$(CGHCPPROXYCMD_SRC_LIB))
CGHCPPROXYCMD_SRC := $(patsubst %,$(DIRCGHCPPROXYCMD)/%,$(CGHCPPROXYCMD_SRC))

CGHCPPROXYCMD_OBJ_LIB := $(patsubst %.c,%.o,$(CGHCPPROXYCMD_SRC_LIB))
CGHCPPROXYCMD_OBJ := $(patsubst %.c,%.o,$(CGHCPPROXYCMD_SRC))

CGHCPPROXYCMD_DEP_LIB := $(patsubst %.c,%.d,$(CGHCPPROXYCMD_SRC_LIB))
CGHCPPROXYCMD_DEP := $(patsubst %.c,%.d,$(CGHCPPROXYCMD_SRC))

CFLAGS_CGHCPPROXYCMD := -I$(DIRCLILIB)
LIBS_CGHCPPROXYCMD := $(DIRCLILIB)/libclilib.a

MAKEFILES_CGHCPPROXYCMD := $(DIRCGHCPPROXYCMD)/module.mk

.PHONY: CGHCPPROXYCMD clean_CGHCPPROXYCMD distclean_CGHCPPROXYCMD unit_CGHCPPROXYCMD $(LCCGHCPPROXYCMD) clean_$(LCCGHCPPROXYCMD) distclean_$(LCCGHCPPROXYCMD) unit_$(LCCGHCPPROXYCMD)

$(LCCGHCPPROXYCMD): CGHCPPROXYCMD
clean_$(LCCGHCPPROXYCMD): clean_CGHCPPROXYCMD
distclean_$(LCCGHCPPROXYCMD): distclean_CGHCPPROXYCMD
unit_$(LCCGHCPPROXYCMD): unit_CGHCPPROXYCMD

CGHCPPROXYCMD: $(DIRCGHCPPROXYCMD)/libcghcpproxycmd.a $(DIRCGHCPPROXYCMD)/cghcpproxycmd

unit_CGHCPPROXYCMD:
	@true

$(DIRCGHCPPROXYCMD)/libcghcpproxycmd.a: $(CGHCPPROXYCMD_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPROXYCMD)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRCGHCPPROXYCMD)/cghcpproxycmd: $(DIRCGHCPPROXYCMD)/cghcpproxycmd.o $(LIBS_CGHCPPROXYCMD) $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPROXYCMD)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_CGHCPPROXYCMD)

$(CGHCPPROXYCMD_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPROXYCMD)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_CGHCPPROXYCMD)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_CGHCPPROXYCMD)

$(CGHCPPROXYCMD_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_CGHCPPROXYCMD)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_CGHCPPROXYCMD)

clean_CGHCPPROXYCMD:
	rm -f $(CGHCPPROXYCMD_OBJ) $(CGHCPPROXYCMD_DEP)

distclean_CGHCPPROXYCMD: clean_CGHCPPROXYCMD
	rm -f $(DIRCGHCPPROXYCMD)/libcghcpproxycmd.a $(DIRCGHCPPROXYCMD)/cghcpproxycmd

-include $(DIRCGHCPPROXYCMD)/*.d
